########################
##
## Leonard Mada
## [the one and only]
##
## Differential Equations
## ODEs: Linear Combinations
##
## draft v.0.1a

### Linear ODEs
# Generated by "Linear" combinations of elementary functions;


### Example of Combinations:

### 2 Polynomial-Radicals
# Base:
# y = b1(x) * P(x)^(1/n1) + b2(x) * Q(x)^(1/n2) + F0(x);

### Note:
# - for Exponential combinations, see:
#   DE.ODE.Exponentials.Linear.R


####################

### Helper Functions

source("Polynomials.Helper.R")
source("DE.ODE.Helper.R")


#######################
#######################

### Linear Combinations

### y = x * (x^2 + b1)^(1/2) + (x^3 + b2)^(1/3) + f0;

# D =>
dy - (x^2 + b1)^(1/2) - x^2 / (x^2 + b1)^(1/2) - x^2 / (x^3 + b2)^(2/3) - df0 # = 0
# (x^2 + b1)*(x^3 + b2) * dy =
(2*x^2 + b1)*(x^3 + b2)*(x^2 + b1)^(1/2) + (x^4 + b1*x^2)*(x^3 + b2)^(1/3) +
	+ (x^2 + b1)*(x^3 + b2) * df0;

# Linear System:
# (x^2 + b1)^(1/2) * ((x^5 + b1*x^3) - (2*x^2 + b1)*(x^3 + b2)) =
(x^2 + b1)*(x^2*y - (x^3 + b2) * dy - x^2*f0 + (x^3 + b2) * df0)
# (x^3 + b2)^(1/3) * ((2*x^2 + b1)*(x^3 + b2) - (x^5 + b1*x^3)) =
((2*x^2 + b1)*(x^3 + b2)*(y - f0) - x*dy + x*(x^2 + b1)*(x^3 + b2) * df0);

# D2 =>
# # (x^2 + b1)*(x^3 + b2) * d2y + (5*x^4 + 3*b1*x^2 + 2*b2*x) * dy =
(5*x^4 + 3*b1*x^2 + 2*b2*x)*(x^2 + b1)^(1/2) +
	+ x * (2*x^2 + b1)*(x^3 + b2)*(x^2 + b1)^(-1/2) +
	+ (4*x^3 + 2*b1*x)*(x^3 + b2)^(1/3) +
	+ x^2 * (x^4 + b1*x^2)*(x^3 + b2)^(-2/3) +
	+ (x^2 + b1)*(x^3 + b2) * d2f0 +
	+ (5*x^4 + 3*b1*x^2 + 2*b2*x) * df0;

### ODE:
# TODO

